version: 2
jobs:
  build:
    working_directory: ~/reviews
    docker:
      - image: circleci/node:7.10
      - image: mongo:3.4.4
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: yarn install
      - run: yarn add jest
      - run: yarn add enzyme
      - run: yarn add react
      - run: yarn add react-test-renderer
      - run: yarn add babel-core
      - run: babel-loader
      - run: babel-preset-es2015
      - run: babel-preset-react
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test